import {
  decodeExecutionManifest,
  decodeSchemaManifest,
  digestExecutionManifest,
  digestSchemaManifest,
  type LogicalType,
  type SchemaColumn,
  type SchemaManifest,
  type SchemaTable,
} from '@chronolog/ir'

import { fromBase64Url, toBase64Url } from './ir.js'

export type GenerateSchemaBindingsOptions = {
  /** Module imported by the generated TypeScript. */
  readonly clientImport?: string
} & (
  | { readonly executionManifest: Uint8Array; readonly executionManifestDigest?: never }
  | { readonly executionManifest?: never; readonly executionManifestDigest: Uint8Array | string }
)

export interface GeneratedSchemaBindingModule {
  readonly source: string
  readonly schemaName: string
  readonly schemaDigest: string
  readonly executionManifestDigest: string
  readonly tables: readonly string[]
}

/**
 * Generates reviewable TypeScript solely from canonical inputs. The output has
 * no timestamp, host path, locale-sensitive ordering, or process metadata.
 */
export async function generateSchemaBindingModule(
  canonicalSchema: Uint8Array,
  options: GenerateSchemaBindingsOptions,
): Promise<GeneratedSchemaBindingModule> {
  const schema = decodeSchemaManifest(Uint8Array.from(canonicalSchema))
  const [schemaDigestBytes, executionManifestDigest] = await Promise.all([
    digestSchemaManifest(schema),
    resolveExecutionDigest(options),
  ])
  const schemaDigest = toBase64Url(schemaDigestBytes)
  const tables = schema.objects
    .filter((object): object is SchemaTable => object.kind === 'table')
    .slice()
    .sort(compareDeclarations)
  const names = generatedNames(tables)
  const source = renderModule(
    schema,
    schemaDigest,
    executionManifestDigest,
    tables,
    names,
    options.clientImport ?? '@chronolog/client',
  )
  return Object.freeze({
    source,
    schemaName: schema.name,
    schemaDigest,
    executionManifestDigest,
    tables: Object.freeze(tables.map((table) => table.name)),
  })
}

/** Concise API for build scripts and the `schema-generate` CLI route. */
export async function generateSchemaBindings(
  canonicalSchema: Uint8Array,
  options: GenerateSchemaBindingsOptions,
): Promise<string> {
  return (await generateSchemaBindingModule(canonicalSchema, options)).source
}

async function resolveExecutionDigest(options: GenerateSchemaBindingsOptions): Promise<string> {
  if (options.executionManifest !== undefined) {
    const manifest = decodeExecutionManifest(Uint8Array.from(options.executionManifest))
    return toBase64Url(await digestExecutionManifest(manifest))
  }
  const bytes = typeof options.executionManifestDigest === 'string'
    ? fromBase64Url(options.executionManifestDigest)
    : Uint8Array.from(options.executionManifestDigest)
  if (bytes.byteLength !== 32) throw new RangeError('Execution-manifest digest must contain exactly 32 bytes')
  const canonical = toBase64Url(bytes)
  if (typeof options.executionManifestDigest === 'string' && canonical !== options.executionManifestDigest) {
    throw new TypeError('Execution-manifest digest must use canonical unpadded base64url')
  }
  return canonical
}

interface Names {
  readonly value: string
  readonly type: string
}

function generatedNames(tables: readonly SchemaTable[]): ReadonlyMap<number, Names> {
  const usedValues = new Set<string>()
  const usedTypes = new Set<string>(['ChronologSqlReadDatabase'])
  const result = new Map<number, Names>()
  for (const table of tables) {
    const rawValue = TYPESCRIPT_RESERVED.has(table.name) ? `${table.name}Table` : table.name
    const rawType = pascalCase(table.name) || `Table${table.id}`
    const value = uniqueIdentifier(rawValue, table.id, usedValues)
    const type = uniqueIdentifier(rawType, table.id, usedTypes)
    result.set(table.id, { value, type })
  }
  return result
}

function uniqueIdentifier(candidate: string, id: number, used: Set<string>): string {
  const safe = /^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(candidate) && !TYPESCRIPT_RESERVED.has(candidate)
    ? candidate
    : `table${id}`
  const result = used.has(safe) ? `${safe}_${id}` : safe
  used.add(result)
  return result
}

function pascalCase(value: string): string {
  return value.split(/_+/u).filter(Boolean).map((part) => `${part[0]?.toUpperCase() ?? ''}${part.slice(1)}`).join('')
}

function renderModule(
  schema: SchemaManifest,
  schemaDigest: string,
  executionManifestDigest: string,
  tables: readonly SchemaTable[],
  names: ReadonlyMap<number, Names>,
  clientImport: string,
): string {
  if (clientImport.length === 0 || /[\r\n\u2028\u2029]/u.test(clientImport)) throw new TypeError('Client import must be a non-empty single-line specifier')
  const lines: string[] = [
    '// Generated by @chronolog/client from canonical schema bytes. Do not edit.',
    `import { defineGeneratedColumn, defineGeneratedTable } from ${JSON.stringify(clientImport)}`,
    `import type { CanonicalJsonValue, DecimalFor, DurationMs, GeneratedSchemaBindings, TimestampMs, Uuid, VectorValue } from ${JSON.stringify(clientImport)}`,
    '',
    `export const SCHEMA_NAME = ${JSON.stringify(schema.name)} as const`,
    `export const SCHEMA_DIGEST = ${JSON.stringify(schemaDigest)} as const`,
    `export const EXECUTION_MANIFEST_DIGEST = ${JSON.stringify(executionManifestDigest)} as const`,
    'export const schemaBindings: GeneratedSchemaBindings = Object.freeze({',
    '  schemaDigest: SCHEMA_DIGEST,',
    '  executionManifestDigest: EXECUTION_MANIFEST_DIGEST,',
    '})',
  ]

  for (const table of tables) {
    const generated = names.get(table.id)!
    const columns = table.columns.slice().sort(compareDeclarations)
    lines.push('', ...renderTableTypes(table, columns, generated.type), '')
    lines.push(`export const ${generated.value} = defineGeneratedTable<${generated.type}Row, ${generated.type}Insert, ${generated.type}Update>()({`)
    lines.push(`  id: ${table.id},`)
    lines.push(`  name: ${JSON.stringify(table.name)},`)
    lines.push(`  declarationOrder: ${table.declarationOrder},`)
    lines.push(`  withoutRowId: ${String(table.withoutRowId)},`)
    lines.push('  columns: {')
    for (const column of columns) {
      const applicationType = columnType(column.valueType.logical)
      lines.push(`    ${JSON.stringify(column.name)}: defineGeneratedColumn<${applicationType}>()({`)
      lines.push(`      id: ${column.id}, name: ${JSON.stringify(column.name)}, declarationOrder: ${column.declarationOrder},`)
      lines.push(`      logicalType: ${logicalTypeSource(column.valueType.logical)}, nullable: ${String(column.valueType.nullable)},`)
      lines.push(`      hasDefault: ${String(column.defaultValue !== undefined)}, generated: ${String(column.generated !== undefined)},`)
      lines.push('    }),')
    }
    lines.push('  },')
    const primary = table.constraints.find((constraint) => constraint.kind === 'primary_key')
    const columnNames = new Map(columns.map((column) => [column.id, column.name]))
    const primaryNames = primary?.columnIds.map((id) => columnNames.get(id)).filter((name): name is string => name !== undefined) ?? []
    lines.push(`  primaryKey: [${primaryNames.map((name) => JSON.stringify(name)).join(', ')}],`)
    lines.push('})')
  }
  lines.push('', 'export interface ChronologSqlReadDatabase {')
  for (const table of tables) {
    const generated = names.get(table.id)!
    lines.push(`  readonly ${JSON.stringify(table.name)}: ${generated.type}Row`)
  }
  lines.push('}')
  lines.push('')
  return lines.join('\n')
}

function renderTableTypes(table: SchemaTable, columns: readonly SchemaColumn[], type: string): string[] {
  const lines = [`export interface ${type}Row {`]
  for (const column of columns) lines.push(propertyLine(column, false))
  lines.push('}', '', `export interface ${type}Insert {`)
  for (const column of columns) {
    if (column.generated !== undefined) continue
    lines.push(propertyLine(column, column.defaultValue !== undefined || column.valueType.nullable))
  }
  lines.push('}', '', `export interface ${type}Update {`)
  for (const column of columns) {
    if (column.generated !== undefined) continue
    lines.push(propertyLine(column, true))
  }
  lines.push('}')
  const primary = table.constraints.find((constraint) => constraint.kind === 'primary_key')
  if (primary !== undefined) {
    const keys = primary.columnIds
      .map((id) => columns.find((column) => column.id === id)?.name)
      .filter((name): name is string => name !== undefined)
    lines.push(
      '',
      `export type ${type}Key = Pick<${type}Row, ${keys.map((name) => JSON.stringify(name)).join(' | ')}>`,
    )
  }
  return lines
}

function propertyLine(column: SchemaColumn, optional: boolean): string {
  const type = `${columnType(column.valueType.logical)}${column.valueType.nullable ? ' | null' : ''}`
  return `  readonly ${JSON.stringify(column.name)}${optional ? '?' : ''}: ${type}`
}

function columnType(type: LogicalType): string {
  switch (type.kind) {
    case 'boolean': return 'boolean'
    case 'int64': return 'bigint'
    case 'decimal': return `DecimalFor<${type.precision}, ${type.scale}>`
    case 'text': return 'string'
    case 'blob': return 'Uint8Array'
    case 'uuid': return 'Uuid'
    case 'timestamp_ms': return 'TimestampMs'
    case 'duration_ms': return 'DurationMs'
    case 'json': return 'CanonicalJsonValue'
    case 'vector': return `VectorValue<${JSON.stringify(type.element)}, ${type.dimensions}, ${vectorStorage(type.element)}>`
  }
}

function vectorStorage(element: Extract<LogicalType, { kind: 'vector' }>['element']): string {
  switch (element) {
    case 'i8': return 'Int8Array'
    case 'u8': return 'Uint8Array'
    case 'i16': return 'Int16Array'
    case 'i32': return 'Int32Array'
    case 'f32': return 'Float32Array'
    case 'f64': return 'Float64Array'
  }
}

function logicalTypeSource(type: LogicalType): string {
  switch (type.kind) {
    case 'boolean': case 'int64': case 'uuid': case 'timestamp_ms': case 'duration_ms': case 'json':
      return `{ kind: ${JSON.stringify(type.kind)} }`
    case 'decimal': return `{ kind: "decimal", precision: ${type.precision}, scale: ${type.scale} }`
    case 'text': return `{ kind: "text", collation: ${JSON.stringify(type.collation)} }`
    case 'blob': return `{ kind: "blob"${type.maxBytes === undefined ? '' : `, maxBytes: ${type.maxBytes}`} }`
    case 'vector': return `{ kind: "vector", element: ${JSON.stringify(type.element)}, dimensions: ${type.dimensions} }`
  }
}

function compareDeclarations(
  left: { readonly declarationOrder: number; readonly id: number; readonly name: string },
  right: { readonly declarationOrder: number; readonly id: number; readonly name: string },
): number {
  return left.declarationOrder - right.declarationOrder || left.id - right.id || (left.name < right.name ? -1 : left.name > right.name ? 1 : 0)
}

const TYPESCRIPT_RESERVED = new Set([
  'await', 'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger', 'default', 'delete',
  'do', 'else', 'enum', 'export', 'extends', 'false', 'finally', 'for', 'function', 'if', 'implements',
  'import', 'in', 'instanceof', 'interface', 'let', 'new', 'null', 'package', 'private', 'protected',
  'public', 'return', 'static', 'super', 'switch', 'this', 'throw', 'true', 'try', 'typeof', 'undefined',
  'var', 'void', 'while', 'with', 'yield',
])
