import {
  encodeExecutionManifest,
  encodeSchemaManifest,
  portableExecutionManifestFixture,
  portableSchemaManifestFixture,
  type LogicalType,
  type SchemaColumn,
  type SchemaManifest,
} from '@chronolog/ir'
import { describe, expect, it } from 'vitest'

import { generateSchemaBindingModule, generateSchemaBindings } from './schema-codegen.js'

const executionBytes = encodeExecutionManifest(portableExecutionManifestFixture())

describe('canonical schema binding generation', () => {
  it('emits a stable reviewable module snapshot', async () => {
    const source = await generateSchemaBindings(
      encodeSchemaManifest(portableSchemaManifestFixture()),
      { executionManifest: executionBytes },
    )

    expect(source).toMatchInlineSnapshot(`
      "// Generated by @chronolog/client from canonical schema bytes. Do not edit.
      import { defineGeneratedColumn, defineGeneratedTable } from "@chronolog/client"
      import type { CanonicalJsonValue, DecimalFor, DurationMs, GeneratedSchemaBindings, TimestampMs, Uuid, VectorValue } from "@chronolog/client"

      export const SCHEMA_NAME = "fixture" as const
      export const SCHEMA_DIGEST = "5Bxy5jKHk_Kk19pQJZWrRJrTBSVC8f1FD95eirR596I" as const
      export const EXECUTION_MANIFEST_DIGEST = "NV4KWF_iQaFyuV7HZTcPn09S9DZw9H5ARbRg5EVFG_U" as const
      export const schemaBindings: GeneratedSchemaBindings = Object.freeze({
        schemaDigest: SCHEMA_DIGEST,
        executionManifestDigest: EXECUTION_MANIFEST_DIGEST,
      })

      export interface ItemsRow {
        readonly "id": bigint
        readonly "value": string
      }

      export interface ItemsInsert {
        readonly "id": bigint
        readonly "value": string
      }

      export interface ItemsUpdate {
        readonly "id"?: bigint
        readonly "value"?: string
      }

      export type ItemsKey = Pick<ItemsRow, "id">

      export const items = defineGeneratedTable<ItemsRow, ItemsInsert, ItemsUpdate>()({
        id: 1,
        name: "items",
        declarationOrder: 0,
        withoutRowId: false,
        columns: {
          "id": defineGeneratedColumn<bigint>()({
            id: 2, name: "id", declarationOrder: 0,
            logicalType: { kind: "int64" }, nullable: false,
            hasDefault: false, generated: false,
          }),
          "value": defineGeneratedColumn<string>()({
            id: 3, name: "value", declarationOrder: 1,
            logicalType: { kind: "text", collation: "binary" }, nullable: false,
            hasDefault: false, generated: false,
          }),
        },
        primaryKey: ["id"],
      })

      export interface ChronologSqlReadDatabase {
        readonly "items": ItemsRow
      }
      "
    `)
  })

  it('is byte-for-byte deterministic and accepts an already computed execution digest', async () => {
    const schemaBytes = encodeSchemaManifest(portableSchemaManifestFixture())
    const first = await generateSchemaBindingModule(schemaBytes, { executionManifest: executionBytes })
    const second = await generateSchemaBindingModule(Uint8Array.from(schemaBytes), {
      executionManifestDigest: first.executionManifestDigest,
    })

    expect(second).toEqual(first)
    expect(first.tables).toEqual(['items'])
    expect(Object.isFrozen(first)).toBe(true)
    expect(first.source).not.toContain(process.cwd())
    expect(first.source).not.toMatch(/generated (?:at|on)/iu)
  })

  it('covers every core logical type and preserves insert/update optionality', async () => {
    const module = await generateSchemaBindingModule(
      encodeSchemaManifest(allTypesSchema()),
      { executionManifestDigest: new Uint8Array(32).fill(7) },
    )

    const required = [
      'readonly "flag": boolean',
      'readonly "count": bigint',
      'readonly "amount"?: DecimalFor<12, 3>',
      'readonly "note"?: string | null',
      'readonly "payload": Uint8Array',
      'readonly "identifier": Uuid',
      'readonly "created_at": TimestampMs',
      'readonly "elapsed": DurationMs',
      'readonly "metadata": CanonicalJsonValue',
      'readonly "embedding": VectorValue<"f32", 3, Float32Array>',
      'readonly "count"?: bigint',
      'logicalType: { kind: "decimal", precision: 12, scale: 3 }',
      'primaryKey: ["count"]',
      'readonly "measurements": MeasurementsRow',
    ]
    for (const fragment of required) expect(module.source).toContain(fragment)
  })

  it('rejects malformed digests and non-canonical schema bytes', async () => {
    await expect(generateSchemaBindings(
      encodeSchemaManifest(portableSchemaManifestFixture()),
      { executionManifestDigest: Uint8Array.of(1, 2, 3) },
    )).rejects.toThrow('exactly 32 bytes')
    await expect(generateSchemaBindings(
      Uint8Array.of(0xff),
      { executionManifestDigest: new Uint8Array(32) },
    )).rejects.toThrow()
  })
})

function allTypesSchema(): SchemaManifest {
  const definitions: readonly [string, LogicalType, boolean?, boolean?][] = [
    ['flag', { kind: 'boolean' }],
    ['count', { kind: 'int64' }],
    ['amount', { kind: 'decimal', precision: 12, scale: 3 }, false, true],
    ['note', { kind: 'text', collation: 'unicode_codepoint' }, true],
    ['payload', { kind: 'blob', maxBytes: 1_024 }],
    ['identifier', { kind: 'uuid' }],
    ['created_at', { kind: 'timestamp_ms' }],
    ['elapsed', { kind: 'duration_ms' }],
    ['metadata', { kind: 'json' }],
    ['embedding', { kind: 'vector', element: 'f32', dimensions: 3 }],
  ]
  const columns: SchemaColumn[] = definitions.map(([name, logical, nullable = false, hasDefault = false], index) => ({
    id: index + 2,
    name,
    declarationOrder: index,
    valueType: { logical, nullable },
    ...(hasDefault ? { defaultValue: { kind: 'decimal' as const, coefficient: 0n, scale: 0 } } : {}),
  }))
  return {
    version: 1,
    name: 'all_types',
    objects: [{
      kind: 'table',
      id: 1,
      name: 'measurements',
      declarationOrder: 0,
      columns,
      constraints: [{ kind: 'primary_key', id: 20, name: 'measurements_pk', columnIds: [3] }],
      withoutRowId: true,
    }],
    seedRows: [],
    functionIds: [],
    collationIds: [],
    moduleIds: [],
  }
}
